import 'package:flutter/widgets.dart';

import '../model/device_spec.dart';

const punchHole = ScreenCutout(
  shape: CutoutShape.punchHole,
  size: Size(26, 26),
  offset: Offset(0, 14),
);

const androidFrame = DeviceFrame(
  bezel: EdgeInsets.all(9),
  outerRadius: 46,
  bodyColor: Color(0xFF232326),
  edgeColor: Color(0xFF5A5A60),
  buttons: [
    DeviceButton(AxisDirection.right, 0.16, 0.07),
    DeviceButton(AxisDirection.right, 0.26, 0.11),
  ],
);

const tabletFrame = DeviceFrame(
  bezel: EdgeInsets.all(16),
  outerRadius: 30,
  bodyColor: Color(0xFF232326),
  edgeColor: Color(0xFF5A5A60),
);

DeviceScreen android(
  Size size, {
  double pixelRatio = 2.625,
  double top = 48,
  double bottom = 24,
  double radius = 34,
  List<ScreenCutout> cutouts = const [punchHole],
  String label = 'Main',
  HingeSpec? hinge,
  Orientation natural = Orientation.portrait,
}) =>
    DeviceScreen(
      label: label,
      logicalSize: size,
      pixelRatio: pixelRatio,
      safeArea: EdgeInsets.only(top: top, bottom: bottom),
      safeAreaRotated: EdgeInsets.only(bottom: bottom),
      cutouts: cutouts,
      cornerRadius: radius,
      hinge: hinge,
      naturalOrientation: natural,
    );

DeviceSpec androidPhone({
  required String id,
  required String name,
  required String vendor,
  required List<DeviceScreen> screens,
  required int year,
  double? diagonal,
  DeviceCategory category = DeviceCategory.phone,
  DeviceFrame frame = androidFrame,
}) =>
    DeviceSpec(
      id: id,
      name: name,
      vendor: vendor,
      platform: DevicePlatform.android,
      category: category,
      diagonalInches: diagonal,
      releaseYear: year,
      frame: frame,
      screens: screens,
    );

final List<DeviceSpec> pixelDevices = [
  androidPhone(
    id: 'google.pixel-10-pro-xl',
    name: 'Pixel 10 Pro XL',
    vendor: 'Google',
    diagonal: 6.8,
    year: 2025,
    screens: [android(const Size(448, 998), pixelRatio: 3.0)],
  ),
  androidPhone(
    id: 'google.pixel-10-pro',
    name: 'Pixel 10 Pro',
    vendor: 'Google',
    diagonal: 6.3,
    year: 2025,
    screens: [android(const Size(412, 919), pixelRatio: 3.0)],
  ),
  androidPhone(
    id: 'google.pixel-10',
    name: 'Pixel 10',
    vendor: 'Google',
    diagonal: 6.3,
    year: 2025,
    screens: [android(const Size(412, 919))],
  ),
  androidPhone(
    id: 'google.pixel-9-pro-xl',
    name: 'Pixel 9 Pro XL',
    vendor: 'Google',
    diagonal: 6.8,
    year: 2024,
    screens: [android(const Size(448, 998), pixelRatio: 3.0)],
  ),
  androidPhone(
    id: 'google.pixel-9-pro',
    name: 'Pixel 9 Pro',
    vendor: 'Google',
    diagonal: 6.3,
    year: 2024,
    screens: [android(const Size(412, 919), pixelRatio: 3.0)],
  ),
  androidPhone(
    id: 'google.pixel-9',
    name: 'Pixel 9',
    vendor: 'Google',
    diagonal: 6.3,
    year: 2024,
    screens: [android(const Size(411, 923))],
  ),
  androidPhone(
    id: 'google.pixel-8-pro',
    name: 'Pixel 8 Pro',
    vendor: 'Google',
    diagonal: 6.7,
    year: 2023,
    screens: [android(const Size(412, 892), pixelRatio: 3.0)],
  ),
  androidPhone(
    id: 'google.pixel-8',
    name: 'Pixel 8',
    vendor: 'Google',
    diagonal: 6.2,
    year: 2023,
    screens: [android(const Size(412, 915))],
  ),
  androidPhone(
    id: 'google.pixel-8a',
    name: 'Pixel 8a',
    vendor: 'Google',
    diagonal: 6.1,
    year: 2024,
    screens: [android(const Size(411, 914))],
  ),
  androidPhone(
    id: 'google.pixel-7-pro',
    name: 'Pixel 7 Pro',
    vendor: 'Google',
    diagonal: 6.7,
    year: 2022,
    screens: [android(const Size(412, 892), pixelRatio: 3.5)],
  ),
  androidPhone(
    id: 'google.pixel-7',
    name: 'Pixel 7',
    vendor: 'Google',
    diagonal: 6.3,
    year: 2022,
    screens: [android(const Size(412, 915))],
  ),
  androidPhone(
    id: 'google.pixel-6a',
    name: 'Pixel 6a',
    vendor: 'Google',
    diagonal: 6.1,
    year: 2022,
    screens: [android(const Size(411, 914))],
  ),
  androidPhone(
    id: 'google.pixel-5',
    name: 'Pixel 5',
    vendor: 'Google',
    diagonal: 6.0,
    year: 2020,
    screens: [android(const Size(393, 851), pixelRatio: 2.75)],
  ),
  androidPhone(
    id: 'google.pixel-4a',
    name: 'Pixel 4a',
    vendor: 'Google',
    diagonal: 5.8,
    year: 2020,
    screens: [android(const Size(393, 851), pixelRatio: 2.75)],
  ),
  androidPhone(
    id: 'google.pixel-tablet',
    name: 'Pixel Tablet',
    vendor: 'Google',
    diagonal: 10.95,
    year: 2023,
    category: DeviceCategory.tablet,
    frame: tabletFrame,
    screens: [
      android(
        const Size(1000, 1600),
        pixelRatio: 1.8,
        top: 24,
        radius: 14,
        cutouts: const [],
      ),
    ],
  ),
];

final List<DeviceSpec> samsungDevices = [
  androidPhone(
    id: 'samsung.galaxy-s25-ultra',
    name: 'Galaxy S25 Ultra',
    vendor: 'Samsung',
    diagonal: 6.9,
    year: 2025,
    screens: [
      android(const Size(384, 832), pixelRatio: 3.75, top: 32, radius: 20),
    ],
  ),
  androidPhone(
    id: 'samsung.galaxy-s25-plus',
    name: 'Galaxy S25+',
    vendor: 'Samsung',
    diagonal: 6.7,
    year: 2025,
    screens: [android(const Size(384, 832), pixelRatio: 3.0, top: 32)],
  ),
  androidPhone(
    id: 'samsung.galaxy-s25',
    name: 'Galaxy S25',
    vendor: 'Samsung',
    diagonal: 6.2,
    year: 2025,
    screens: [android(const Size(360, 780), pixelRatio: 3.0, top: 32)],
  ),
  androidPhone(
    id: 'samsung.galaxy-s24-ultra',
    name: 'Galaxy S24 Ultra',
    vendor: 'Samsung',
    diagonal: 6.8,
    year: 2024,
    screens: [
      android(const Size(384, 824), pixelRatio: 3.75, top: 32, radius: 20),
    ],
  ),
  androidPhone(
    id: 'samsung.galaxy-s24-plus',
    name: 'Galaxy S24+',
    vendor: 'Samsung',
    diagonal: 6.7,
    year: 2024,
    screens: [android(const Size(384, 854), pixelRatio: 3.0, top: 32)],
  ),
  androidPhone(
    id: 'samsung.galaxy-s24',
    name: 'Galaxy S24',
    vendor: 'Samsung',
    diagonal: 6.2,
    year: 2024,
    screens: [android(const Size(360, 780), pixelRatio: 3.0, top: 32)],
  ),
  androidPhone(
    id: 'samsung.galaxy-s23-ultra',
    name: 'Galaxy S23 Ultra',
    vendor: 'Samsung',
    diagonal: 6.8,
    year: 2023,
    screens: [
      android(const Size(384, 824), pixelRatio: 3.75, top: 32, radius: 20),
    ],
  ),
  androidPhone(
    id: 'samsung.galaxy-s23',
    name: 'Galaxy S23',
    vendor: 'Samsung',
    diagonal: 6.1,
    year: 2023,
    screens: [android(const Size(360, 780), pixelRatio: 3.0, top: 32)],
  ),
  androidPhone(
    id: 'samsung.galaxy-s22',
    name: 'Galaxy S22',
    vendor: 'Samsung',
    diagonal: 6.1,
    year: 2022,
    screens: [android(const Size(360, 780), pixelRatio: 3.0, top: 32)],
  ),
  androidPhone(
    id: 'samsung.galaxy-s21',
    name: 'Galaxy S21',
    vendor: 'Samsung',
    diagonal: 6.2,
    year: 2021,
    screens: [android(const Size(360, 800), pixelRatio: 3.0, top: 32)],
  ),
  androidPhone(
    id: 'samsung.galaxy-a55',
    name: 'Galaxy A55',
    vendor: 'Samsung',
    diagonal: 6.6,
    year: 2024,
    screens: [android(const Size(384, 854), pixelRatio: 2.8125, top: 32)],
  ),
  androidPhone(
    id: 'samsung.galaxy-a35',
    name: 'Galaxy A35',
    vendor: 'Samsung',
    diagonal: 6.6,
    year: 2024,
    screens: [android(const Size(384, 854), pixelRatio: 2.8125, top: 32)],
  ),
  androidPhone(
    id: 'samsung.galaxy-a16',
    name: 'Galaxy A16',
    vendor: 'Samsung',
    diagonal: 6.7,
    year: 2024,
    screens: [android(const Size(393, 873), pixelRatio: 2.75, top: 32)],
  ),
  androidPhone(
    id: 'samsung.galaxy-tab-s10-ultra',
    name: 'Galaxy Tab S10 Ultra',
    vendor: 'Samsung',
    diagonal: 14.6,
    year: 2024,
    category: DeviceCategory.tablet,
    frame: tabletFrame,
    screens: [
      android(
        const Size(800, 1232),
        pixelRatio: 2.0,
        top: 24,
        radius: 12,
        cutouts: const [],
      ),
    ],
  ),
  androidPhone(
    id: 'samsung.galaxy-tab-s9',
    name: 'Galaxy Tab S9',
    vendor: 'Samsung',
    diagonal: 11.0,
    year: 2023,
    category: DeviceCategory.tablet,
    frame: tabletFrame,
    screens: [
      android(
        const Size(753, 1205),
        pixelRatio: 2.0,
        top: 24,
        radius: 12,
        cutouts: const [],
      ),
    ],
  ),
];

const _bookHinge = HingeSpec(axis: Axis.vertical);

DeviceSpec _foldable({
  required String id,
  required String name,
  required String vendor,
  required int year,
  required double diagonal,
  required DeviceScreen main,
  required DeviceScreen cover,
}) =>
    androidPhone(
      id: id,
      name: name,
      vendor: vendor,
      year: year,
      diagonal: diagonal,
      category: DeviceCategory.foldable,
      screens: [main, cover],
    );

final List<DeviceSpec> foldableDevices = [
  _foldable(
    id: 'samsung.galaxy-z-fold-7',
    name: 'Galaxy Z Fold 7',
    vendor: 'Samsung',
    year: 2025,
    diagonal: 8.0,
    main: android(
      const Size(716, 794),
      pixelRatio: 2.75,
      top: 32,
      radius: 16,
      cutouts: const [],
      hinge: _bookHinge,
    ),
    cover: android(
      const Size(360, 840),
      pixelRatio: 3.0,
      top: 32,
      radius: 24,
      label: 'Cover',
    ),
  ),
  _foldable(
    id: 'samsung.galaxy-z-fold-6',
    name: 'Galaxy Z Fold 6',
    vendor: 'Samsung',
    year: 2024,
    diagonal: 7.6,
    main: android(
      const Size(707, 823),
      pixelRatio: 2.625,
      top: 32,
      radius: 16,
      cutouts: const [],
      hinge: _bookHinge,
    ),
    cover: android(
      const Size(323, 792),
      pixelRatio: 3.0,
      top: 32,
      radius: 22,
      label: 'Cover',
    ),
  ),
  _foldable(
    id: 'samsung.galaxy-z-fold-5',
    name: 'Galaxy Z Fold 5',
    vendor: 'Samsung',
    year: 2023,
    diagonal: 7.6,
    main: android(
      const Size(674, 841),
      pixelRatio: 2.625,
      top: 32,
      radius: 16,
      cutouts: const [],
      hinge: _bookHinge,
    ),
    cover: android(
      const Size(320, 792),
      pixelRatio: 3.0,
      top: 32,
      radius: 22,
      label: 'Cover',
    ),
  ),
  _foldable(
    id: 'samsung.galaxy-z-fold-4',
    name: 'Galaxy Z Fold 4',
    vendor: 'Samsung',
    year: 2022,
    diagonal: 7.6,
    main: android(
      const Size(674, 841),
      pixelRatio: 2.625,
      top: 32,
      radius: 16,
      cutouts: const [],
      hinge: _bookHinge,
    ),
    cover: android(
      const Size(320, 772),
      pixelRatio: 3.0,
      top: 32,
      radius: 22,
      label: 'Cover',
    ),
  ),
  _foldable(
    id: 'google.pixel-10-pro-fold',
    name: 'Pixel 10 Pro Fold',
    vendor: 'Google',
    year: 2025,
    diagonal: 8.0,
    main: android(
      const Size(791, 820),
      pixelRatio: 2.625,
      radius: 16,
      cutouts: const [],
      hinge: _bookHinge,
    ),
    cover: android(
      const Size(411, 923),
      pixelRatio: 2.625,
      radius: 26,
      label: 'Cover',
    ),
  ),
  _foldable(
    id: 'google.pixel-9-pro-fold',
    name: 'Pixel 9 Pro Fold',
    vendor: 'Google',
    year: 2024,
    diagonal: 8.0,
    main: android(
      const Size(791, 820),
      pixelRatio: 2.625,
      radius: 16,
      cutouts: const [],
      hinge: _bookHinge,
    ),
    cover: android(
      const Size(411, 923),
      pixelRatio: 2.625,
      radius: 26,
      label: 'Cover',
    ),
  ),
  _foldable(
    id: 'oneplus.open',
    name: 'OnePlus Open',
    vendor: 'OnePlus',
    year: 2023,
    diagonal: 7.82,
    main: android(
      const Size(706, 775),
      pixelRatio: 2.8,
      top: 32,
      radius: 16,
      cutouts: const [],
      hinge: _bookHinge,
    ),
    cover: android(
      const Size(408, 892),
      pixelRatio: 2.8,
      top: 32,
      radius: 26,
      label: 'Cover',
    ),
  ),
  _foldable(
    id: 'honor.magic-v3',
    name: 'Honor Magic V3',
    vendor: 'Honor',
    year: 2024,
    diagonal: 7.92,
    main: android(
      const Size(725, 800),
      pixelRatio: 2.8,
      top: 32,
      radius: 16,
      cutouts: const [],
      hinge: _bookHinge,
    ),
    cover: android(
      const Size(404, 896),
      pixelRatio: 2.8,
      top: 32,
      radius: 26,
      label: 'Cover',
    ),
  ),
];
