import 'package:flutter/widgets.dart';

import '../model/device_spec.dart';
import 'android_devices.dart';

DeviceSpec _oem({
  required String id,
  required String name,
  required String vendor,
  required Size size,
  required int year,
  double pixelRatio = 3.0,
  double diagonal = 6.7,
  double top = 44,
  double bottom = 24,
  double radius = 30,
}) =>
    androidPhone(
      id: id,
      name: name,
      vendor: vendor,
      year: year,
      diagonal: diagonal,
      screens: [
        android(
          size,
          pixelRatio: pixelRatio,
          top: top,
          bottom: bottom,
          radius: radius,
        ),
      ],
    );

final List<DeviceSpec> oemDevices = [
  _oem(
    id: 'xiaomi.15-ultra',
    name: 'Xiaomi 15 Ultra',
    vendor: 'Xiaomi',
    size: const Size(384, 854),
    year: 2025,
    diagonal: 6.73,
  ),
  _oem(
    id: 'xiaomi.15',
    name: 'Xiaomi 15',
    vendor: 'Xiaomi',
    size: const Size(393, 873),
    year: 2025,
    diagonal: 6.36,
  ),
  _oem(
    id: 'xiaomi.14',
    name: 'Xiaomi 14',
    vendor: 'Xiaomi',
    size: const Size(393, 873),
    year: 2023,
    diagonal: 6.36,
  ),
  _oem(
    id: 'xiaomi.redmi-note-14-pro',
    name: 'Redmi Note 14 Pro',
    vendor: 'Xiaomi',
    size: const Size(393, 873),
    pixelRatio: 2.75,
    year: 2024,
    diagonal: 6.67,
  ),
  _oem(
    id: 'xiaomi.poco-x7-pro',
    name: 'POCO X7 Pro',
    vendor: 'Xiaomi',
    size: const Size(393, 873),
    pixelRatio: 2.75,
    year: 2025,
    diagonal: 6.67,
  ),
  _oem(
    id: 'oneplus.13',
    name: 'OnePlus 13',
    vendor: 'OnePlus',
    size: const Size(412, 919),
    year: 2025,
    diagonal: 6.82,
  ),
  _oem(
    id: 'oneplus.12',
    name: 'OnePlus 12',
    vendor: 'OnePlus',
    size: const Size(412, 919),
    year: 2024,
    diagonal: 6.82,
  ),
  _oem(
    id: 'oneplus.nord-4',
    name: 'OnePlus Nord 4',
    vendor: 'OnePlus',
    size: const Size(393, 873),
    pixelRatio: 2.75,
    year: 2024,
    diagonal: 6.74,
  ),
  _oem(
    id: 'oppo.find-x8-pro',
    name: 'Oppo Find X8 Pro',
    vendor: 'Oppo',
    size: const Size(412, 919),
    year: 2024,
    diagonal: 6.78,
  ),
  _oem(
    id: 'oppo.reno-12',
    name: 'Oppo Reno 12',
    vendor: 'Oppo',
    size: const Size(393, 873),
    pixelRatio: 2.75,
    year: 2024,
    diagonal: 6.7,
  ),
  _oem(
    id: 'vivo.x200-pro',
    name: 'vivo X200 Pro',
    vendor: 'vivo',
    size: const Size(412, 919),
    year: 2024,
    diagonal: 6.78,
  ),
  _oem(
    id: 'vivo.v40',
    name: 'vivo V40',
    vendor: 'vivo',
    size: const Size(393, 873),
    pixelRatio: 2.75,
    year: 2024,
    diagonal: 6.78,
  ),
  _oem(
    id: 'honor.magic-7-pro',
    name: 'Honor Magic 7 Pro',
    vendor: 'Honor',
    size: const Size(412, 919),
    year: 2025,
    diagonal: 6.8,
  ),
  _oem(
    id: 'huawei.pura-70-pro',
    name: 'Huawei Pura 70 Pro',
    vendor: 'Huawei',
    size: const Size(393, 873),
    year: 2024,
    diagonal: 6.8,
  ),
  _oem(
    id: 'nothing.phone-3',
    name: 'Nothing Phone (3)',
    vendor: 'Nothing',
    size: const Size(412, 915),
    pixelRatio: 2.625,
    year: 2025,
    diagonal: 6.7,
  ),
  _oem(
    id: 'nothing.phone-2',
    name: 'Nothing Phone (2)',
    vendor: 'Nothing',
    size: const Size(412, 915),
    pixelRatio: 2.625,
    year: 2023,
    diagonal: 6.7,
  ),
  _oem(
    id: 'sony.xperia-1-vi',
    name: 'Sony Xperia 1 VI',
    vendor: 'Sony',
    size: const Size(411, 960),
    pixelRatio: 3.5,
    year: 2024,
    diagonal: 6.5,
    radius: 12,
  ),
  _oem(
    id: 'sony.xperia-5-v',
    name: 'Sony Xperia 5 V',
    vendor: 'Sony',
    size: const Size(393, 873),
    year: 2023,
    diagonal: 6.1,
    radius: 12,
  ),
  _oem(
    id: 'asus.rog-phone-9',
    name: 'ASUS ROG Phone 9',
    vendor: 'ASUS',
    size: const Size(393, 873),
    year: 2024,
    diagonal: 6.78,
    radius: 16,
  ),
  _oem(
    id: 'asus.zenfone-11-ultra',
    name: 'Zenfone 11 Ultra',
    vendor: 'ASUS',
    size: const Size(412, 919),
    year: 2024,
    diagonal: 6.78,
  ),
  _oem(
    id: 'motorola.edge-50-pro',
    name: 'Motorola Edge 50 Pro',
    vendor: 'Motorola',
    size: const Size(393, 873),
    pixelRatio: 2.75,
    year: 2024,
    diagonal: 6.7,
  ),
  _oem(
    id: 'realme.gt-7-pro',
    name: 'realme GT 7 Pro',
    vendor: 'realme',
    size: const Size(412, 919),
    year: 2024,
    diagonal: 6.78,
  ),
  _oem(
    id: 'tecno.camon-30',
    name: 'TECNO Camon 30',
    vendor: 'TECNO',
    size: const Size(393, 873),
    pixelRatio: 2.75,
    year: 2024,
    diagonal: 6.78,
  ),
  _oem(
    id: 'infinix.note-40-pro',
    name: 'Infinix Note 40 Pro',
    vendor: 'Infinix',
    size: const Size(393, 873),
    pixelRatio: 2.75,
    year: 2024,
    diagonal: 6.78,
  ),
  _oem(
    id: 'generic.android-go',
    name: 'Android Go (entry level)',
    vendor: 'Generic',
    size: const Size(360, 800),
    pixelRatio: 2.0,
    year: 2023,
    diagonal: 6.1,
    top: 24,
    radius: 16,
  ),
];
